name: CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Build Binary
        run: pyinstaller -F rename.py
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: rename-Windows
          path: dist
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/rename-Windows.exe
